name: CI

on:
  pull_request:
    branches: [main] # Triggers when a pull request is made to the main branch

jobs:
  tests_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks out GitHub repo using version 2 of "actions"
      - uses: actions/setup-node@v1 # Sets up Node
        with:
          node-version: 16 # GitHub Actions currently uses Node16
      - name: Install dependencies
        run: npm install
      - name: Run tests and coverage
        run: npm test && cat coverage/lcov.info | node_modules\coveralls\bin\coveralls.js
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.0.0
<<<<<<< HEAD
        
=======

>>>>>>> 7ffcb60 (Initial Commit)
  prettier_check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 # Checks out GitHub repo using version 2 of "actions"
        - uses: actions/setup-node@v1 # Sets up Node
          with:
            node-version: 16 # GitHub Actions currently uses Node16
        - name: Check style
          run: npx prettier --check *.js # Checks if the files are stylistically correct
